# Generated by Django 5.2 on 2026-07-22 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_type', models.CharField(choices=[('own', 'I am submitting my own dataset'), ('recommend', 'I am recommending a dataset for the GDEX repository')], default='own', max_length=20)),
                ('dsid', models.CharField(blank=True, default='', max_length=10)),
                ('dataset_title', models.CharField(default='', max_length=500)),
                ('dataset_abstract', models.CharField(default='', max_length=5000)),
                ('dataset_details', models.CharField(default='', max_length=5000)),
                ('dataset_size_mb', models.FloatField(default=0)),
                ('hpc_access', models.BooleanField(default=False)),
                ('cif_fare_contributors', models.BooleanField(default=False)),
                ('is_ncar_employee', models.BooleanField(default=False)),
                ('data_policy_agreement', models.BooleanField(default=False)),
                ('data_deposit_agreement', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatasetLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(default='', max_length=500)),
                ('access_method', models.CharField(default='', max_length=20)),
                ('access_verification', models.CharField(blank=True, choices=[('', 'Not verified'), ('readable', 'Verified readable (/glade)'), ('reachable', 'Verified reachable (https)')], default='', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='datasubmit.submission')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]