# Generated by Django 5.2 on 2026-08-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasubmit', '0002_submission_created_submission_submitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submission_decision',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='submission_status',
            field=models.CharField(choices=[('pending_decision', 'Pending Decision'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('published', 'Published'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], default='pending_decision', max_length=20),
        ),
    ]
