# Generated by Django 5.2 on 2026-08-10 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasubmit', '0003_submission_submission_decision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='cif_fare_contributors',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='data_deposit_agreement',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='data_policy_agreement',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dataset_abstract',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dataset_details',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='dataset_title',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='hpc_access',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='is_ncar_employee',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_decision',
        ),
        migrations.AddField(
            model_name='submission',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dataset_size_mb',
            field=models.FloatField(default=-9999),
        ),
        migrations.CreateModel(
            name='PreSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_title', models.CharField(default='', max_length=500)),
                ('dataset_abstract', models.CharField(default='', max_length=5000)),
                ('dataset_details', models.CharField(default='', max_length=5000)),
                ('hpc_access', models.BooleanField(default=False)),
                ('cif_fare_contributors', models.BooleanField(default=False)),
                ('is_ncar_employee', models.BooleanField(default=False)),
                ('data_policy_agreement', models.BooleanField(default=False)),
                ('data_deposit_agreement', models.BooleanField(default=False)),
                ('submission_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_submissions', to='datasubmit.submission')),
            ],
        ),
    ]
