# Generated by Django 5.2 on 2026-08-11 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasubmit', '0004_remove_submission_cif_fare_contributors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='presubmission',
            old_name='submission_id',
            new_name='submission',
        ),
        migrations.RemoveField(
            model_name='datasetlocation',
            name='access_verification',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_status',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='submission_type',
        ),
        migrations.AddField(
            model_name='datasetlocation',
            name='data_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datasetlocation',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetlocation',
            name='is_checking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetlocation',
            name='reachable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datasetlocation',
            name='readable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_wishlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='datasetlocation',
            name='order',
            field=models.PositiveIntegerField(default=9999),
        ),
        migrations.AlterField(
            model_name='submission',
            name='dsid',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_decision', 'Pending Decision'), ('in_progress', 'In Progress'), ('in_review', 'In Review'), ('published', 'Published'), ('canceled', 'Canceled'), ('deleted', 'Deleted')], default='pending_decision', max_length=20)),
                ('order', models.PositiveIntegerField(default=9999)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='datasubmit.submission')),
            ],
        ),
    ]
