replicaCount: 1

webapp:
  name: gdex-webserver
  group: gdex-web
  path: /
  tls:
    fqdn: riley.k8s.ucar.edu
    fqdnGDEX: riley.ucar.edu
    fqdnAPI: riley-api.ucar.edu
    secretName: incommon-cert-riley-gdex-webserver
  container: 
    image: hub.k8s.ucar.edu/riley_gdex_test/gdex-web-portal:v19083182179
    port: 8080
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 4Gi
      cpu: 4
    responseTimeout: 180
    maxUploadSize: 60m
  ingress:
    ingressClassName: nginx-internal
    oldrdaRedirect: false
    oldesgRedirect: false
    oldrdaRedirect: false
    oldtdsRedirect: false

volume:
  enabled: true
  readonly: true
  fs:
    existingClaim: gdexdata
    name: gdexdata
    mountPath: /data
