replicaCount: 1

app:
  name: gdex-webserver
  group: gdex-web
  path: /
  tls:
    fqdn: gdex.k8s.ucar.edu
    secretName: incommon-cert-gdex-webserver
  container: 
    image: docker.io/dattore/gdex-web-portal:v30
    port: 8080
    memory: 56G
    cpu: 6

volume:
  fs:
    name: gdexdata
    size: 55Gi
    mountPath: /data
  glade:
    name: glade-campaign
    server: gladedm1.ucar.edu
    path: /gpfs/csfs1
    mountPath: /glade/campaign
    readOnly: true
