replicaCount: 1

webapp:
  name: gdex-webserver
  group: gdex-web
  path: /
  tls:
    fqdn: gdex.k8s.ucar.edu
    fqdnGDEX: gdex.ucar.edu
    fqdnAPI: api.gdex.ucar.edu
    secretName: incommon-cert-gdex-webserver
  container: 
    image: docker.io/dattore/gdex-web-portal:v345
    port: 8080
    requests:
      memory: 4Gi
      cpu: 1
    limits:
      memory: 16Gi
      cpu: 6
    responseTimeout: 180
    maxUploadSize: 60m
  ingress:
    ingressClassName: nginx-external

volume:
  fs:
    name: gdexdata
    size: 2Ti
    mountPath: /data
