replicaCount: 1

webapp:
  name: gdex-webserver-test
  group: gdex-web-test
  path: /
  tls:
    fqdn: gdex-web-test.k8s.ucar.edu
    secretName: incommon-cert-gdex-web-test
  container: 
    image: docker.io/dattore/gdex-web-portal:v145
    port: 443
    memory: 1G
    cpu: 2
