Alias /static /usr/local/gdexweb/static
Alias /media /data/local/gdexweb/media
Alias /css /data/web/css
Alias /images /data/web/images
Alias /js /data/web/js
Alias /php /data/web/php
Alias /rda_pg_config /data/web/rda_pg_config
