Alias /static /usr/local/gdexweb/static
Alias /media /data/local/gdexweb/media
Alias /css /data/web/css
Alias /images /data/web/images
Alias /js /data/web/js
Alias /metadata /data/web/metadata
Alias /php /data/web/php
Alias /rda_pg_config /data/web/rda_pg_config
Alias /schemas /data/web/metadata/schemas
Alias /gdexdocs /data/web/gdexdocs
AliasMatch "^/datasets/(d[0-9]{6})/metadata/(.*)$" "/data/web/datasets/$1/metadata/$2"
