{{ if not .Values.testName }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volume.fs.name }}
  namespace: {{ .Release.Namespace}}
spec:
  accessModes:
    - ReadWriteMany
  volumeName: pvc-91135cc3-4f9a-44a5-9b32-ccbe7bb004ba
  resources:
    requests:
      storage: {{ .Values.volume.fs.size | default "1Gi" }} 
{{ end }}
