{{ if not .Values.enableTest }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-old-api.rda
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://api.gdex.ucar.edu$request_uri"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - api.rda.k8s.ucar.edu
      - api.rda.ucar.edu
      secretName: incommon-cert.api.rda.k8s.ucar.edu
  rules:
  - host: api.rda.k8s.ucar.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
  - host: api.rda.ucar.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
{{ end }}
