apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-old-esg
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://gdex.ucar.edu"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - esg.k8s.ucar.edu
      - earthsystemgrid.org
      - www.earthsystemgrid.org
      secretName: letsencrypt-cert-2.esg.k8s.ucar.edu
  rules:
  - host: esg.k8s.ucar.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
  - host: earthsystemgrid.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
  - host: www.earthsystemgrid.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
