{{ if not .Values.testName }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-old-esg
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
#    nginx.ingress.kubernetes.io/permanent-redirect: "https://esg.k8s.ucar.edu"
spec:
  ingressClassName: nginx-internal
  tls:
    - hosts:
      - earthsystemgrid.org
      - www.earthsystemgrid.org
      secretName: letsencrypt-cert-3.esg.k8s.ucar.edu
  rules:
  - host: earthsystemgrid.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gdex-webserver
            port:
              number: 8080
  - host: www.earthsystemgrid.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: gdex-webserver
            port:
              number: 8080
{{ end }}
