apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-old-rda
  namespace: {{ .Release.Namespace }}
  labels:
    group: {{ .Values.webapp.group }}
  annotations:
    cert-manager.io/cluster-issuer: "incommon"
    nginx.ingress.kubernetes.io/permanent-redirect: "https://gdex.ucar.edu"
spec:
  ingressClassName: nginx-external
  tls:
    - hosts:
      - rda.k8s.ucar.edu
      - rda.ucar.edu
      secretName: incommon-cert.rda.k8s.ucar.edu
  rules:
  - host: rda.k8s.ucar.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
  - host: rda.ucar.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-dummy
            port:
              number: 80
