{{- if .Values.webapp.ingress.oldrdaRedirect }}
apiVersion: v1
kind: Service
metadata:
  name: service-dummy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    group: {{ .Values.webapp.group }}
spec:
  ports:
    - port: 80
{{- end }}