apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
    group: {{ .Values.webapp.group }}
spec:
  ports:
  - port: {{ .Values.webapp.container.port }}
  selector:
    app: {{ .Release.Name }}-{{ .Values.webapp.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
