StartServers               32
ServerLimit               100
ThreadsPerChild            50
MaxRequestWorkers        2500
MinSpareThreads          1250
MaxSpareThreads          2500
MaxConnectionsPerChild  10000
