# Generated by Django 4.0.8 on 2024-08-13 15:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('dashboard_sections', wagtail.fields.StreamField([('dashboard_section', wagtail.blocks.StructBlock([('section_label', wagtail.blocks.CharBlock(default='', help_text='Title for the section in the dashboard', max_length=30, required=True)), ('button_label', wagtail.blocks.CharBlock(default='', help_text='Text of an optional button for the section', max_length=20, required=False)), ('button_position', wagtail.blocks.ChoiceBlock(blank=False, choices=[('TR', 'Top/Right'), ('BR', 'Bottom/Right')], help_text='Position of the optional button for the section (Top/Right is the default)'))]))], default='', use_json_field=None, verbose_name='List of Dashboard Sections')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
