# Generated by Django 5.2 on 2026-03-26 21:02

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardpage',
            name='version',
            field=models.CharField(default='1.0', help_text='The dashboard version identifier', max_length=10),
        ),
        migrations.AlterField(
            model_name='dashboardpage',
            name='dashboard_sections',
            field=wagtail.fields.StreamField(
                [('dashboard_section', 3)], 
                block_lookup={
                    0: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Title for the section in the dashboard', 'max_length': 50, 'required': True}), 
                    1: ('wagtail.blocks.CharBlock', (), {'default': '', 'help_text': 'Text of an optional button for the section', 'max_length': 20, 'required': False}), 
                    2: ('wagtail.blocks.ChoiceBlock', [], {'blank': False, 'choices': [('TR', 'Top/Right'), ('BR', 'Bottom/Right')], 'help_text': 'Position of the optional button for the section (Top/Right is the default)'}), 
                    3: ('wagtail.blocks.StructBlock', [[('section_label', 0), ('button_label', 1), ('button_position', 2)]], {})
                }, 
                default='', 
                verbose_name='List of Dashboard Sections'
            ),
        ),
    ]
