# Generated by Django 4.0.8 on 2025-05-04 17:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetadataFormatsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('metadata_formats', wagtail.fields.StreamField([('metadata_format', wagtail.blocks.StructBlock([('prefix', wagtail.blocks.CharBlock(default='', help_text='Prefix for this metadata format', max_length=30, required=True)), ('schema', wagtail.blocks.CharBlock(default='', help_text='XML schema for this metadata format', max_length=255, required=True)), ('namespace', wagtail.blocks.CharBlock(default='', help_text='XML namespace of schema for this metadata format', max_length=255, required=True))]))], default='List of exportable metadata formats', use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
