# Generated by Django 5.2 on 2026-01-14 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 14), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 14), verbose_name='Start date'),
        ),
    ]
