# Generated by Django 5.2 on 2026-01-15 03:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_staffpage_menu_title_alter_alertmessage_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentationpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AddField(
            model_name='genericpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AddField(
            model_name='metricspage',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AddField(
            model_name='newshome',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AddField(
            model_name='redirectpage',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 1, 15), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 1, 15), verbose_name='Start date'),
        ),
    ]
