# Generated by Django 5.2 on 2026-03-26 21:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_documentationpage_menu_title_genericpage_menu_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 3, 26), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 3, 26), verbose_name='Start date'),
        ),
    ]
