# Generated by Django 4.0.8 on 2025-05-13 23:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_alertmessage_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 5, 13), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2025, 5, 13), verbose_name='Start date'),
        ),
    ]
