# Generated by Django 5.2 on 2026-05-19 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_featuredcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='card_1_footer_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_1_footer_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_1_icon_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_1_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_1_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_2_footer_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_2_footer_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_2_icon_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_2_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_2_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_3_footer_page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_3_footer_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_3_icon_name',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_3_text',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='card_3_title',
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 5, 19), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 5, 19), verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='featuredcard',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='homepagesearchsuggestion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
