# Generated by Django 5.2 on 2026-05-21 21:07

import datetime
import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_homepage_card_1_footer_page_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestHomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tagline', models.CharField(default='', max_length=100)),
                ('welcome', wagtail.fields.RichTextField(default='')),
                ('search_box_title', models.CharField(default='', max_length=255, verbose_name='Search Box Title')),
                ('search_box_placeholder', models.CharField(default='', max_length=255, verbose_name='Search Box Placeholder')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 5, 21), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 5, 21), verbose_name='Start date'),
        ),
        migrations.CreateModel(
            name='TestHomePageFeaturedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(default='', help_text='Title of the card to be displayed on the home page.', max_length=255, verbose_name='Title')),
                ('icon_name', models.CharField(blank=True, default='', help_text='Icon name class from the fontawesome icon set. See fontawesome version 6 documentation for more info. Either Icon or Icomoon Icon Name can be used to specify an icon for the card.  If both are specified, Icon will take precedence over Icomoon Icon Name.', max_length=50, verbose_name='Icon')),
                ('icomoon_icon_name', models.CharField(blank=True, default='', help_text='(Optional) If using a custom SVG icon from the gdex icomoon set, specify the icon class name here.  Custom icomoon icons can be viewed and added to the gdex custom icon set by adding the SVG to the static/unity/lib/icomoon2/ directory and including the icon class name here. This field is only necessary if the desired icon is not available in the fontawesome icon set.', max_length=50, verbose_name='Icomoon Icon Name')),
                ('text', wagtail.fields.RichTextField(default='', help_text='Body text to be displayed on the home page card.', verbose_name='Body Text')),
                ('card_url', models.URLField(blank=True, help_text='External URL to link to from the card.  If both Card URL and Card Page are provided, Card Page will take precedence.', null=True, verbose_name='Card URL')),
                ('card_page', models.ForeignKey(blank=True, help_text='Internal page to link to from the card. If both Card Page and Card URL are provided, Card Page will take precedence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Card Page')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_cards', to='home.testhomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestHomePageSearchSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('search_term', models.CharField(help_text='Search term displayed under the home page search bar as a search suggestion badge.  For example, "AI Ready Datasets" or "Zarr Format Datasets".', max_length=25, verbose_name='Search Term')),
                ('search_term_url', models.CharField(help_text='Search term URL specified as the GDEX Search URL to link to when the search term is clicked.  This can be a relative URL or absolute URL. For example, a relative URL could be /gsearch/dataset-search/?q=&filter-match-all.tags=AI%20Ready and an absolute URL could be https://gdex.ucar.edu/gsearch/dataset-search/?q=&filter-match-all.tags=AI%20Ready to link to a search for AI-Ready datasets.', max_length=255, verbose_name='Search Term URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_suggestions', to='home.testhomepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
