# Generated by Django 5.2 on 2026-06-22 17:30

import datetime
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_testhomepage_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhomepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='testhomepage',
            name='hero_heading',
            field=models.CharField(blank=True, default='The system of record for Earth system science.', help_text='Main heading text after the highlighted word', max_length=200),
        ),
        migrations.AddField(
            model_name='testhomepage',
            name='hero_heading_highlight',
            field=models.CharField(blank=True, default='GDEX.', help_text='First word shown in blue e.g. "GDEX."', max_length=50),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 6, 22), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 6, 22), verbose_name='Start date'),
        ),
    ]
