# Generated by Django 5.2 on 2026-06-23 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_testhomepage_hero_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decsstaff',
            options={'ordering': ['name'], 'verbose_name': 'DECS Staff Member', 'verbose_name_plural': 'DECS Staff Members'},
        ),
        migrations.AlterModelOptions(
            name='newsauthor',
            options={'ordering': ['name'], 'verbose_name': 'News Author', 'verbose_name_plural': 'News Authors'},
        ),
        migrations.AddField(
            model_name='decsstaff',
            name='first_name',
            field=models.CharField(default='DECS', help_text='DECS staff member first name', max_length=100),
        ),
        migrations.AddField(
            model_name='decsstaff',
            name='last_name',
            field=models.CharField(default='Staff Member', help_text='DECS staff member last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 6, 23), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 6, 23), verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='decsstaff',
            name='name',
            field=models.CharField(default='DECS Staff Member', help_text='DECS staff member full name', max_length=100),
        ),
    ]
