# Generated by Django 5.2 on 2026-06-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_decsstaff_options_alter_newsauthor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhomepagefeaturedcard',
            name='card_link_text',
            field=models.CharField(default='Learn more', help_text="Text displayed for the link to the related URL.  Default='Learn more'", max_length=100),
        ),
        migrations.AddField(
            model_name='testhomepagesearchsuggestion',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional short description of the search term to be displayed under the search term badge.  For example, "Datasets prepared for AI/ML applications" or "Cloud-optimized array data".', max_length=100, verbose_name='Search Term Description'),
        ),
    ]
