# Generated by Django 5.2 on 2026-07-23 18:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_testhomepagefeaturedcard_card_link_text_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhomepage',
            name='metrics_banner_image',
            field=models.ForeignKey(blank=True, help_text='Metrics banner image displayed at the bottom of the home page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 7, 23), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 7, 23), verbose_name='Start date'),
        ),
    ]
