# Generated by Django 5.2 on 2026-07-29 19:22

import datetime
import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_testhomepage_metrics_banner_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredcard',
            name='card_link_text',
            field=models.CharField(default='Learn more', help_text="Text displayed for the link to the related URL.  Default='Learn more'", max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='banner_image',
            field=models.ForeignKey(blank=True, help_text='Hero banner image displayed at the top of the home page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_description',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading',
            field=models.CharField(blank=True, default='The system of record for Earth system science.', help_text='Main heading text after the highlighted word', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_heading_highlight',
            field=models.CharField(blank=True, default='GDEX.', help_text='First word shown in blue e.g. "GDEX."', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='metrics_banner_image',
            field=models.ForeignKey(blank=True, help_text='Metrics banner image displayed at the bottom of the home page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepagesearchsuggestion',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional short description of the search term to be displayed under the search term badge.  For example, "Datasets prepared for AI/ML applications" or "Cloud-optimized array data".', max_length=100, verbose_name='Search Term Description'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 7, 29), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 7, 29), verbose_name='Start date'),
        ),
    ]
