# Generated by Django 5.2 on 2026-09-21 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_featuredcard_card_link_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesearchsuggestion',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Icon name class from the fontawesome icon set to be displayed in the search suggestion chip.', max_length=50, verbose_name='Icon'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='end_date',
            field=models.DateField(default=datetime.date(2026, 9, 21), verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='alertmessage',
            name='start_date',
            field=models.DateField(default=datetime.date(2026, 9, 21), verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='homepagesearchsuggestion',
            name='description',
            field=models.CharField(blank=True, default='', help_text='Optional short description of the search term to be displayed in the search suggestion chip.  For example, "Datasets prepared for AI/ML applications" or "Cloud-optimized array data".', max_length=100, verbose_name='Search Term Description'),
        ),
        migrations.AlterField(
            model_name='homepagesearchsuggestion',
            name='search_term',
            field=models.CharField(help_text='Search term displayed under the home page search bar as a search suggestion chip.  For example, "AI Ready Datasets" or "Zarr Format Datasets".', max_length=25, verbose_name='Search Term'),
        ),
        migrations.AlterField(
            model_name='homepagesearchsuggestion',
            name='search_term_url',
            field=models.CharField(help_text='Search term URL specified as the GDEX Search URL to link to when the search term is clicked.  This can be a relative URL or absolute URL. For example, a relative URL could be /gsearch/dataset-search/?q=&filter-match-any.tags=AI%20Ready and an absolute URL could be https://gdex.ucar.edu/gsearch/dataset-search/?q=&filter-match-any.tags=AI%20Ready to link to a search for AI-Ready datasets.', max_length=255, verbose_name='Search Term URL'),
        ),
    ]
