# Generated by Django 5.2 on 2026-03-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daashome',
            name='menu_title',
            field=models.CharField(blank=True, default='', help_text='Short title to use in the navigation bar menu.  If blank, the page title will be used.', max_length=50),
        ),
    ]
