# Generated by Django 4.0.8 on 2024-08-13 15:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookForDataPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('refine_filters', wagtail.fields.StreamField([('filter_data', wagtail.blocks.StructBlock([('id', wagtail.blocks.CharBlock(default='', max_length=10, required=True)), ('title', wagtail.blocks.CharBlock(default='', max_length=30, required=True)), ('description', wagtail.blocks.CharBlock(default='', required=True)), ('query_table', wagtail.blocks.CharBlock(default='', help_text='Absolute name of database table for dataset queries', max_length=50, required=False))]))], default='', use_json_field=None, verbose_name='List of Refine Filters')),
                ('results_title', models.CharField(default='', max_length=100, verbose_name='Title for Results Pane')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
