# Generated by Django 4.0.8 on 2024-08-13 15:47

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetamanCategoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('tab_title', models.CharField(default='', max_length=100, verbose_name='Title of the tab for this category')),
                ('menu', wagtail.fields.StreamField([('menu_item', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(default='', help_text='Title of this menu action', max_length=30, required=True)), ('description', wagtail.blocks.CharBlock(default='', help_text='Brief description (255 chars max) of this menu action', max_length=255, required=True)), ('requires_existing_dsid', wagtail.blocks.BooleanBlock(default=False, help_text='Check this box if an existing dataset ID is required for this action', required=False))]))], default='', use_json_field=None, verbose_name='Menu of actions for this category')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='MetamanPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
